Added polarion metadata for all automated test cases
windup/windup_integration_test pull request #67
Opened 2021-03-01 06:37 UTC by ganeshhubale

- Added TODO for not convered cases as per steps

Signed-off-by: Ganesh Hubale <ghubale@redhat.com>

2021-03-02 04:46 UTC, nitishSr commented on mta/tests/test_projects.py
> +        caseimportance: High
Please confirm the letter casing here, small case has been used everywhere other than this (High)

2021-03-02 04:47 UTC, nitishSr approved these changes
Just one comment to consider, otherwise looks good to me !

2021-03-03 05:06 UTC, sshveta requested changes

2021-03-03 05:06 UTC, sshveta commented on mta/tests/test_advanced_options_Test06.py
> +        casecomponent: Web-console
Sorry Ganesh , I think we should do WebConsole as case component, please change

2021-03-04 04:07 UTC, sshveta approved these changes

2021-03-04 04:08 UTC, merged